version: '3.7'
services:
    app:
        image: taranovegor/tomsg_bot:latest
        container_name: tomsg_bot
        restart: on-failure
        environment:
            - DEBUG
            - LOG_LEVEL
            - TELEGRAM_BOT_TOKEN
            - TELEGRAM_BASE_URL
            - INSTAGRAM_VIDEO_PARSER_URL
            - INSTAGRAM_ENCRYPTION_KEY
            - REDDIT_CLIENT_ID
            - REDDIT_CLIENT_SECRET
            - REDDIT_APP_OWNER_USERNAME
            - TIKTOK_VIDEO_RESOURCE_URL
            - TIKTOK_THUMBNAIL_RESOURCE_URL
            - GA_MEASUREMENT_ID
            - GA_SECRET
            - GA_UID_SALT
            - VK_THUMBNAIL_URL
            - YOUTUBE_API_KEY
